### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by spiyush0212** [spiyush0212/TASCA-The-Automatic-Screenshot-Capturing-App#3]
Handle the case when the number of screenshots entered is not an integer. Eg; 1.5

**Comment by alimustafashah** [comment]
Can you assign this task to me?

**Comment by spiyush0212** [comment]
Yes sure, done!

**Comment by spiyush0212** [comment]
Hey, I just noticed emanNahed worked on this same issue and his PR has been merged as well. So you do not need to work on this now, thanks a lot for showing your interest in my project. If you feel like, you may work on a different issue or create a new issue if you can. Thanks again!

**Comment by alimustafashah** [comment]
Okay no problem!
