### ISSUE TITLE
Include error handling

### ISSUE THREAD

**Issue by spiyush0212** [spiyush0212/TASCA-The-Automatic-Screenshot-Capturing-App#8]
Let's say the user enters a negative time in the program. Currently, the code will only handle 1 error input by user. So when the give an error input again. The program will fail and terminate. I would like the error handling to be continuous in nature.

**Comment by spiyush0212** [comment]
You can look at the closed PR by emanNahed for more information on this issue.

**Comment by Ares358** [comment]
Interesting. Can you assign this to me?

**Comment by spiyush0212** [comment]
@Ares358 Yes sure, done! Make a PR once you are done :) All the best!
