### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by spiyush0212** [spiyush0212/TASCA-The-Automatic-Screenshot-Capturing-App#9]
I tried to create a decent ReadMe for the project, but I think we can make a better ReadMe that is more welcoming for people that use this project for the first time. Maybe we can add some more information about the project. Add some short GIFs or images and make use of varied font styles to convey our content in a better way.

**Comment by Kirsan98** [comment]
Hi I want to do it, please can you assign me ?

**Comment by spiyush0212** [comment]
@Kirsan98 yes sure! thanks for showing interest! if possible, please make sure to get familiar with the app before writing the readme.

**Comment by spiyush0212** [comment]
Hey @Kirsan98 I have merged your PR on the main branch but somehow I do not see your name in the list of contributors. Do you know why is that so? If that doesn't bother you then it's alright but it would have been great to have your name there. I tried looking up online but couldn't find the reason. Maybe you can give it a shot?

**Comment by Kirsan98** [comment]
Hi @spiyush0212, I don't know why, tbh this is my first contribution. Maybe it was because my git email was not the same that my GitHub email. I linked them but it didn't change anything, it is weird because I can see my forks on your project. I looked on the internet but I didn’t find anything similar to my issue. I will see in future contributions if it changes, thanks for warning.

**Comment by Kirsan98** [comment]
I found it 
"Commit was made less than 24 hours ago. After making a commit that meets the requirements to count as a contribution, you may need to wait for up to 24 hours to see the contribution appear on your contributions graph."
**source** : https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Comment by spiyush0212** [comment]
Hey Kirsan, it's been over 36 hours now and I still don't see your name in the list. If you want you can create a new PR on the readme with some minor changes and that might add you on the list. But in case it doesn't matter to you, please let me know. I will close this issue now! Thank you so much for your contributions!

**Comment by Kirsan98** [comment]
Hi @spiyush0212, as you can see I created new PR. I hope this time it will work. Otherwise, you can close this issue. Thanks for the help!.

**Comment by spiyush0212** [comment]
Merged, and it shows in the list now, great!
